import ArticlesHero from '@/components/ArticlesHero'
import styles from '../../components/peleador.module.css'
import yorgelis from '@/assets/peleadores/yorgelis.jpg'

export default function Salazar () {
    return(
        <main className={styles.peleador}>
            <ArticlesHero title='Yorgelis Salazar' img={yorgelis} />
            <section className={styles.peleador__article}>
                <h2 className={styles.peleador__article__subtitle}>Yorgelis Salazar Karate</h2>
                <p className={styles.peleador__article__text}>Yorgelis Salazar, es una karateka venezolana nacida el 10 de noviembre de 1997 en Ciudad Bolivar del Estado de Bolivar. La artista marcial venezolana hizo historia en 2022 al voncertirse en la mejor karateca del mundo, en la categoría femenina de kumite de 50 kilos. Yorgelis ganó la medalla de oro en la Premier League 1 que se disputó en Azerbaiyán, en la ciudad de Bakú. En dicha ocasión se convirtió en la primer venezolana en conseguir el puesto #1 en el ranking mundial del karate femenino, luego de terminar la competencia internacional invicta y vencer a la iraní <b>sara Bahmanyar</b> 5-0 en la final.</p>
                <p className={styles.peleador__article__text}>La karateka nacida en Bolivar, comenzó a entrenar karate a los 9 años de edad, tiempo en el que rapidamente comenzó a tener éxito, al ganar 2 medallas de plata en su primera competencia.</p>
                <p className={styles.peleador__article__text}>La artista marcial venezolana se estuvo preparando para los Juegos Olimpicos de Tokio 2020 que debido a la pandemia se celebraron en 2021, pero lamentablemente su sueño se vió truncado por una rotura de ligamentros cruzados en la rodilla que la vió obligada a retirarse de los eventos clasificatorios para la cometición. Este fue un traspie muy complicado para la venezolana que en una entrevista contó como fue el proceso de recuperación, de lo que además es una lesión muy dura: &quot;Pasé como un mes llorando cada día. Todo en mi teléfono y en el alrededor era Tokio y cuando vi el momento del karate en los Juegos Olímpicos y vi a mis compañeras con las que me he enfrentado y que les había ganado, me dolió mucho. Luego lo tomé como motivación, dije: ‘soy joven, mi carrera deportiva apenas comienza’. Y hoy me siento muy bien, lo que pasó tenía una razón y debo seguir adelante&quot;</p>
                <p className={styles.peleador__article__text}>Sin embargo, el futuro traería mejores cosas para Yorgelis, que en 2022 supo ganar el oro de forma dominante en la Premier League 1, el certamen de karate más importante del mundo. Torneo en el que ya había ganado 2 medallas de bronce, en los eventos celebrados en Emiratos Árabes Unidos, y en el celebrado en Marruecos.</p>
                <p className={styles.peleador__article__text}>Además de que lograría el oro de esta competición una vez más en septiembre de 2023, en el evento celebrado de Dublín, capital de Irlanda. En donde por la categoría de 50 kilos, lograría vencer en la final a la croata <b>Ema Sgardelly</b>, con un marcador perfecto de 6-0. Luego de esta victoria quisó agradecer a su familia y a quienes la apoyaron por medio de sus redes sociales: &quot;Hice lo mejor que pude y me divertí mucho haciendo lo que amo. Gracias a mi pequeño equipo y a mi familia que siempre están detrás de mí. Un agradecimiento especial a @ftjaimenoguera que luchó con mi lesión todo este último mes en Venezuela para recuperarme y lo logró. Gracias también al Dr. @albertolazabal_oly que fue clave en mi recuperación. Y Gracias a todos los que me apoyaron para estar aquí&quot;.</p>
                <p className={styles.peleador__article__text}>Además de estos premios, Salazar ha ganado la medalla de oro representando a su país en los Juegos Sudamericanos Asunción 2022, luego de ganar el evento femenino de kumite de 50 kilos. Además de haber alcanzado su segunda medalla de oro en el Campeonato Mundial senior de Curazao, torneo que igualmente ganó en el año 2021 en Uruguay.</p>
                <p className={styles.peleador__article__text}>Su logro más reciente fue en noviembre de 2023, donde Yorgelis Salazar se coronaría campeona de los Juegos Panamericanos de Santiago 2023 por la categoría de 50 kilogramos, celebrados en Chile. Al vencer a la peleadora canadiense <b>Yamila Lahyanssa</b>, a quien derrotó con una victoria 5-2, que se terminó colgando la medalla plateada. A este último combate, la venezolana llegaba luego de conseguir un triunfo por 8-2 ante la peleadora perteneciente al Equipo de Atletas Independientes (EAI), Bárbara Morales, que terminó recibiendo la medalla de bronce.</p>
            </section>
        </main>
    )
}