import ArticlesHero from '@/components/ArticlesHero'
import styles from '../../../article.module.css'
import defensa from '@/assets/articles-big/defensa_personal.jpg'

export default function Defensa () {
    return(
        <main className={styles.article}>
            <ArticlesHero title='Defensa Personal Karate' img={defensa} />
            <section className={styles.article__container}>
                <h2>¿Qué tan útil es el karate para la defensa personal?</h2>
                <p>Aunque en sus inicios, la utilidad del karate residía en que podían usarse sus técnicas para defenserse en un escenario de pelea real, con el paso del tiempo se fue ablandando un poco, porque su objetivo y su práctica se fue diversificando hacia otros objetivos, dando prioridad a lo deportivo, a lo recreativo y a la visión personal técnica que pudieran tener determinados maestros. Pero esto no es necesariamente malo, dado de que en sus inicios era normal que los alumnos y practicantes del karate perdieran un diente entrenando o se lesionaran de gravedad. Esto ya no es así, de hecho se consideraría una irresponsabilidad grave por parte de un maestro permitir que sus alumnos dañen su salud de esta forma. Todo esto, pese a volver del deporte y la practica del karate algo más seguro, también lo aleja un poco más de lo que es un escenario de combate real.</p>
                <p>Es muy importante saber, que en una situación donde la otra persona está armada con un arma de fuego o con un arma blanca, no hay mucho que hacer, no hay karate que detenga una bala o que sea capaz de ayudarte si estás desangrandote. Por mucho que uno sepa sobre artes marciales en general, hay cosas contras las que uno no se puede enfrentar solo, como dice la frase: &quot;Desde que se inventó la pólvora se jodió el último hombre valiente&quot;, y &quot;El mejor ataque es una buena carrera en sentido contrario&quot;.</p>
                <p>Además de que como en todo deporte, el karate cuenta con unas reglas a las que uno como practicante se debe atener, cosa que no es compatible con una situación real en donde puede estar en juego la vida de uno, o donde el adversario que tengamos delante no se va a atener a las mismas reglas. Esto es importante porque en el deporte no se entrenan situaciones o golpes que podrían darse en la vida real y que acabarían con determinadas situaciones mucho más rápido, como lo son los piquetes de ojos, mordeduras o los golpes en la entrepierna.</p>
                <p>Habiendo hecho todas estas salvedades, está claro que una persona que sabe karate tiene más herramientas para defenderse en situaciones que lo ameriten que una que no tiene idea. Existe un elemento muy entrenado en karate y ese es el autocontrol y el manejo de situaciones de estrés, que pueden ser trasladados a situaciones de la vida cotidiana, más aún en situaciones de peligro, y que son de utilidad en estos escenarios. A diferencia de otras artes marciales donde sólo se aprende a dar golpes, hacer llaves y ponen el foco en lo físico, en el karate existe un gran componente espiritual, de mantener una plena consciencia, de tener un profundo control de las emociones, y de manetener control de la energía, que si no se tienen, es muy difícil ejecutar las ténicas apropiadamente, dado que si te ves envuelto en una situación de mucho estrés, el cuerpo puede fallar y las ténicas que uno tiene aprendidas se vuelven menos efectivas.</p>
                <p>Al final, si lo que se quiere es practicar el karate como defensa personal, se debe cambiar un poco el enfoque de los entrenamientos, ya que estos normalmente, tanto en el karate como en la mayoría de las artes marciales, responden a una necesidad estética, que no siempre responde a la necesidad de la supervivencia en situaciones extremas. Por lo tanto, si se entrena con la intención de defenderse se debe aprender a detener la agresión lo más rápido posible, y es primordial dominar lo básico: Controlar el centro de gravedad, la colocación en el espacio y manipular la energía que se transmite.</p>
            </section>
        </main>
    )
}