import ArticlesHero from '@/components/ArticlesHero'
import styles from '../../../article.module.css'
import enpikata from '@/assets/articles-big/enpi_kata (2).jpg'
import Link from 'next/link'

export default function EnpiKata () {
    return(
        <main className={styles.article}>
            <ArticlesHero title='Enpi Kata' img={enpikata} />
            <section className={styles.article__container}>
                <iframe className={styles.article__video} width="560" height="315" src="https://www.youtube.com/embed/DUI0oon0kNQ?si=A4pJLEamSoIPOXe3" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
                <p>Enpi, que en español se traduce como &quot;El vuelo de la golondrina&quot; es un <Link href='/estilos/karate-kata'>Kata</Link> avanzado del estilo <Link href='/estilos/karate-shotokan'>Shotokan</Link> de karate y se lo considera uno de los más característicos de este estilo, debido a sus movimientos amplios y repentinos, cambios de dirección relámpago y saltos. En otros estilos se lo conoce con el nombre de <b>Wanshu</b>, que es su nombre antiguo y es nombre con el que se conoció a quien se cree que lo creó, Sappushi Wanshu. Se cree que es el resultado de la fusión del Kempo chino y las artes marciales de Okinawa, debido a la historia de origen que este tiene.</p>
                <p>Aunque existen diferentes versiones sobre cómo fue creado este kata, se dice que fue traído a Okinawa por el Sappushi, o el &quot;Enviado Imperial Chino&quot;, Ji Wang (aunque en Okinawa se lo conoció con el nombre de Sappushi Wanshu), en el año 1683 durante el periodo de 6 meses que estuvo en la isla, durante una misión ordenada por el gobierno Qing a la villa de Tomari. Aunque se discute sobre si la estancia de Ji Wang fue demasiado corta como para tener alumnos, se cree que sí los tuvo, y es por esto que el kata representa la herencia de lucha dejada por Wang Ji a sus alumnos, al igual que una semilla contiene la herencia genética de una planta.</p>
                <p>A lo largo de los siglos, con la transmisión de conocimientos, el kata ha cambiado y se han creado varias versiones, cada una con sus propias peculiaridades. Por ejemplo, el Enpi comparte gran parte de la estructura con todos (o casi todos) los estilos modernos, como el Wadoryu, el Wadokai, el Shitoryu, el Seibukan, y otros más antiguos, como el Shorinryu, el Matsubayashiryu, etc. Por estas razones, Enpi se convierte en un claro ejemplo de como las antiguas tradiciones del karate han sido alteradas, modificadas, manipuladas y han cambiado tan profundamente que son irreconocibles.</p>
                <p>El kata fue practicado únicamente en la aldea de Tomari hasta 1870, pasando más tarde a la escuela de Matsumura, siendo adoptado por el Shuri-te de Itoshu, maestro que más adelante terminaría introduciendo cambios. Posteriormentem en la decada de 1920, el padre del karate moderno, el maestro <b>Funakoshi</b>, le cambiaría el nombre al kata, dejando este de ser <b>Wanshu</b> para pasar a conocerse como <b>Enpi</b>, por la forma tan dinámica que tiene este kata, alternando los cambios de nivel altos y bajos, en el nombre quiso dejar reflejado el espíritu inquieto e imprevisible de sus movimientos, con todos los saltos, los cambios rápidos de altura en sus posiciones, los agarres y las entradas veloces, así como los cambios bruscos de dirección, que asemejan las maniobras de las golondrinas en el aire (de ahí su significado y tradicción al español). </p>
                <p>El propio maestro Funakoshi dijo sobre este kata: <b>&quot;La característica distintiva de este kata está en la manera en la que atacas el jo-dan (nivel alto) de tu oponente saltando hacia delante y agarrando y tirando de él hacia ti. Estos movimientos parecen similares a la forma en la que una golondrina puede estar volando alto en un momento, y bajo en el siguiente, esquivando en el acto y girando con habilidad en el aire. Por esta razón he llamado al kata En-pi, o golondrina-volando. &quot;</b></p>
                <p>Este es un kata que consta de 37 movimientos y la aplicación de dicho kata es recomendable cuando en el combate en distancia corta nuestras manos son agarradas u obstaculizadas. También sirve para descubrir formas de apertura de la guardia del oponente, así como mediante fintas o amagos que invitan al ataque, podemos generar situaciones tácticas que nos resulten favorables.</p>
            </section>
        </main>
    )
}