import ArticlesHero from '@/components/ArticlesHero'
import styles from '../../components/peleador.module.css'
import mastatsu from '@/assets/peleadores/masutatsu.jpg'

export default function Masatsu () {
    return(
        <main className={styles.peleador}>
            <ArticlesHero title='Masutatsu Oyama' img={mastatsu} />
            <section className={styles.peleador__article}>
                <h2 className={styles.peleador__article__subtitle}>Karate Mas Oyama</h2>
                <p className={styles.peleador__article__text}>Oyama Masutatsu, más reconocido popularmente como Mas Oyama, fue un maestro de Karate coreano famoso por ser el fundador del estilo Kyokushinkai, nacido el 4 de junio de 1923 en la provincia de Corea del Sur Jeolla del Norte, en la ciudad de Gimje. Sin embargo, vivió la mayor parte de su vida en Japón, donde obtuvo su 4° dan en karate en la Universidad de Takushoku, y en donde estudió en la Universidad de Waseda, en el equipo de Judo.</p>
                <p className={styles.peleador__article__text}>De pequeño, debido a su rebeldía y a las peleas diarias que tenía con su padre, quien bebía mucho y golpeaba a su madre, Oyama fue mandado a la región china de Manchuria para vivir en la granja de su hermana. A los 9 comenzó a estudiar Kung Fu. A los 12 volvió a Corea del Sur donde siguió entrenando artes marciales chinas. Luego viajó a Tokio, capital de Japón, en donde intentó sin mucho éxito volverse piloto. Durante ese tiempo continuó aprendiendo artes marciales, como el Boxeo occidental, el savate, la lucha olimpica y el Judo. Hasta que finalmente fue a entrenar al dojo de la Universidad de Takushoku, donde fue recibido por el maestro <b>Gichin Funakoshi</b>, quien le enseñó el estilo Shokotan de karate. Su rápido progreso impresionó a muchos, dado que para sus 17 años ya era segundo Dan, y para los 20 años ya obtuvo el cuarto Dan.</p>
                <p className={styles.peleador__article__text}>Oyama Masutatsu estuvó entrenando en la academia para el Ejército Imperial Japonés, que se especializaba en la guerra antiguerrilla, el espionaje, el combate cuerpo a cuerpo y con armas de fuego. Permaneció allí 2 años hasta que se disolvió con la llegada de los países aliados a Jaón, al final de la Segunda Guerra Mundial, en 1945.</p>
                <p className={styles.peleador__article__text}>Después de su salida de la academia. Mas Oyama por sugerencia del maestro Chojun Miyagi decidió emprender junto a uno de sus propios estudiantes su retiro a las montañas para fortalecer sus habilidades técnicas y templar su espíritu. Desafortunadamente durante su retiro fue abandonado por su alumno, lo que hizo de esta travesía algo más difícil, dado que además de lidiar con el vigoroso entrenamiento al que se estaba sometiendo, tuvo que lidiar con la soledad y el aislamiento social. Su entrenamiento y retirada a las montañas, duro un total de 18 meses. Unos meses más tarde en 1947, cuando Oyama ya había vuelto a la civilización, participó en el primer Campeonato Nacional de Artes Marciales en la modalidad de Karate, organizado en Japón en la categoría sin peso u open. En dicho torneo salió campeón.</p>
                <p className={styles.peleador__article__text}>Sin embargo después de ganar el campeonato, Masutatsu Oyama se sentía vació por no haber sido capaz de completar los 3 años de aislamiento en las montañas que se había propuesto. Es por eso que esta vez decidido, emprendió un entrenamiento en la montaña de Kiyozumi, donde llego a tener un entrenamiento extremadamente riguroso, 12 horas al día, 7 días a la semana, sin ningún día de descanso. Su entrenamiento constó de sentarse a meditar bajo las frías aguas de las cascadas, luchando con animales salvajes, rompiendo árboles y piedras del río con sus manos, usando los árboles como superficie de golpeo, saltando sobre las plantas de lino, además de incluir un periodo de estudio de los antiguos textos clásicos de las artes marciales basadas en la filosofía Zen.</p>
                <p className={styles.peleador__article__text}>En 1952, viajó por un año a Estados Unidos, demostrando su estilo de karate en vivo en la televisión nacional. Durante los años subsiguientes, Oyama aceptó todos desafíos que le presentaron, llegando a combatir con 270 diferentes luchadores, boxeadores y peleadores. La mayoría de estos combates los ganó de un solo golpe de puño. Los combates nunca duraban más de tres minutos, y la mayoría duró no más de unos pocos segundos</p>
                <p className={styles.peleador__article__text}>En 1953 abrió su primer dojo de entrenamiento de karate en Tokio. Después abrió otro en 1956 que para 1957 ya tenía 700 miembros a pesar de que por la dureza de los entrenamientos tenía un alto porcentaje de abandono.</p>
                <p className={styles.peleador__article__text}>Finalmente, el 26 de abril de 1994 en Tokio, el mundo del karate recibiría la triste noticia de que Masutatsu Oyama, a la edad de 70 años fallecía por un cancer de pulmón. Dejando a cargo de su organización al entonces 5° Dan Akiyoshi Matsui.</p>
            </section>
        </main>
    )
}