import ArticlesHero from '@/components/ArticlesHero'
import styles from '@/app/articulos/article.module.css'
import byakuren from '@/assets/articles-big/byakuren (2).jpg'
import Link from 'next/link'

export default function Byakuren () {
    return(
        <main className={styles.article}>
            <ArticlesHero title='Karate Byakuren' img={byakuren} />
            <section className={styles.article__container}>
                <p>El Byakuren Kaikan es un estilo de karate fundado en 1984 por el <b>Sugihara Masayasu</b>, quien fue un estudiante y guardaespaldas de So Doshin, fundador del Shorinji Kempo. Pese a ser una escuela de karate, debido a la enseñanza que recibió Masayasu por parte de su maestro, el Byakuren es considera como hijo del estilo Shorinji Kempo, que a su vez tiene origenes estrechamente relacionados con el Kung Fu Shaolin.</p>
                <p>Sugihara Masayasu, quien nació en 1951 en Osaka, Japón, comenzó a practicar Judo y <Link href='/articulos/karate-do'>Karate</Link> desde muy joven, hasta que descubriría y comenzaría a entrenar Shorinji Kempo. Para cuando Masayasu tenía 28 años, ya había ganado su 6° <Link href='/articulos/dans-karate'>Dan</Link> en este arte marcial. A esta edad además se convirtió en el guardaespaldas de su maestro So Doshin. Este arte marcial no permitía a sus estudiantes formar parte de una competición real, sin embargo Masayasu estaba desesperado por probar sus habilidades de combate contra algún oponente real, así que decidió inscribirse en una competición de karate. Debido a esto, en 1983 se unió a un torneo organizado por <b>Seido Kaikan</b>, usando el pseudónimo de &quot;Byakuren Kaikan&quot; para su escuela. Masayasu terminó entre los ganadores, y lamentablemente para él la verdad se terminó sabiendo, así que para evitar seguir metiendo en problemas con la organización de Shorinji Kempo, decidió establecer su propio estilo al que llamó algo así como <b>Federación Internacional de Karate-Kempo Byakuren</b> en 1984.</p>
                <p>La razón de su nombre está primero en que así era llamado el cuerpo de seguridad de Shorinji Kempo, &quot;Byakuren&quot;, también porque en el nombre está incluido el nombre de la ténica de un arte marcial, y además, como estaba por comenzar a tomar un nuevo camino en el Karate, tendría que haber comenzado desde del principio usando el cinturón blanco.</p>
                <p>A diferencia de otros estilos y escuela de aquel momento, desde su fundación los miembros comenzaron a participar de diferentes competiciones organizadas por profesionales de diferentes estilos, convirtiendose en unos contendientes. Su fundador incluso, llegó ganarse los apodos de &quot;El maestro de la pelea&quot; y &quot;Invasor&quot; en el mundo del Full Contact Karate. Y desde entonces organizan torneos regionales y nacionales de Full Contact Karate, llegando a organizar incluso, su primer torneo mundial de Karate en Osaka, en el año 2004 cuando estaban cumpliendo 20 años desde su fundación. </p>
                <p>En cuanto a lo ténico, el método mantinene la estructura técnica que tenía el Shorinji Kempo: Go-ho (ténicas fuertes) y Ju-ho (ténicas suaves), usando el Go-ho para los golpeos con puños, las patadas, los rodillazos y los golpes con los codos, estructurado como en las escuelas modernas de Full Contact Karate. Mientras que el Ju-ho se orienta a la defensa personal, utilizando ténicas de derribo, luxación y control que se heredaron del Shorinji Kempo. Es valioso destacar, que a diferencia de otros estilos de karate más tradicionales, el Byakuren cuenta con menos katas, que la mayoría de veces sólo se utilizan durante los test practicados para subir de nivel en cuanto a cinturones.</p>
                <p>También se entrena para fortalecer los musculos y mejorar la condición física, dado que especialmente en las competiciones, es necesario un cierto grado de fuerza, por lo que no sería de extrañar que también se hicieran ejercicios destinados a mejorar la resistencia, la velocidad y el poder. </p>
                <p>A pesar de ser un estilo que hace mucho el foco en la competición, los valores del Byakuren como Asociación son la humilidad, el respeto y el altruismo. La seriedad y la dedicación son necesarias mientras se entrena, pero también lo es el ser capaz de reconocer los limites propios, en pos de evitar lesiones. El objetivo último del dojo, no es el de producir campeones, sino el de ser un lugar para el crecimiento. Lo que se aprenda en el Byakuren Kaikan ddebe ser integrado a la vida personal también con el objetivo de servir de ayuda.</p>
            </section>
        </main>
    )
}