import ArticlesHero from '@/components/ArticlesHero'
import styles from '../../components/peleador.module.css'
import higa from '@/assets/peleadores/higa.jpg'

export default function Higa () {
    return(
        <main className={styles.peleador}>
            <ArticlesHero title='Oscar Higa' img={higa} />
            <section className={styles.peleador__article}>
                <h2 className={styles.peleador__article__subtitle}>Oscar Higa Karate</h2>
                <p className={styles.peleador__article__text}>Oscar Higa es un sensei de Karate Argentino, nacido el 28 de marzo de 1954 en Buenos Aires. Comenzó a entrenar desde muy joven, tomando lecciones privadas de su padre, quien enseñaba a grupos pequeños de japoneses radicados en el país, cuando todavía no existían los gimnasios de karate en Argentina. Durante su juventud, Oscar fue alternando sus estudios de ingeniería, su práctica de karate y su otro gran pasión, la pintura.</p>
                <p className={styles.peleador__article__text}>Su padre, el Maestro Jintatsu Higa, fue una de las mayores influencias para Oscar que recuerda que en algún momento de 1969 le dijo &quot;Si vas detrás de un conejo lo podrás agarrar, de todos modos no es fácil. Pero si vas detrás de dos conejos simultáneamente seguramente no agarrarás ninguno&quot;. Oscar tomó las palabras de su padre, y es entonces cuando decidió abandonar el resto de actividades que tenía para dedicarse de lleno al karate. Desde ese momento, dedica entre 6 y 7 horas al día a su entrenamiento de karate, donde además busca difundir este arte marcial, habiendo abierto escuelas en distintas provincias de Argentina y en distintos puntos de Sudamerica.</p>
                <p className={styles.peleador__article__text}>A lo largo de su carrera, Oscar ha reconocido a su padre el Sensei Jintatsu Higa y a su tío el Sensei Yuchoku Higa como sus principales maestros. Además de mostrarse siempre agradecido con el Sensei Michihisa Itaya, de la Escuela Shotokan quien fue el que lo introdujo en el karate deportivo en la Argentina.</p>
                <p className={styles.peleador__article__text}>Luego de que en el año 1983, su padre falleciera, Oscar Higa se hace cargo de la jefatura de la Escuela Kyudokan en la Argentina. Un par de años más tarde, recibe el grado de 6° Dan y recibe en Okinawa el título de Representante de la Escuela Kyudokan para toda Sudamérica. Finalmente en marzo de 1988, en uno de sus frecuentes viajes a Okinawa obtiene el grado de 7° Dan y le conceden la Representación para toda América y el título de Director Técnico Mundial de la Escuela.</p>
                <p className={styles.peleador__article__text}>Oscar Higa tuvo una vida llena de viajes y cambio de aires. En agosto de 1988 deja la Argentina para instalarse en la ciudad de Los Angeles, Estados Unidos, donde introdujo por primera vez la Escuela Kyudokan en el país Norteamericano. A partir de 1990, el maestro higa comeinza a difundir el Karate Kyudokan en Italia, país en el que reside actualmente, en la ciudad de Palermo, a la que llegó en el año 1995. Incialmente se instala en Milán durante algunos meses, donde estaba su antiguo discípulo Antonio Policrisi. Despues de Milán, viaja a Pádova (Véneto), luego a Lazio, y finalmente antes de su llegada a Palermo, hace un arribo a Sicilia.</p>
                <p className={styles.peleador__article__text}>Actualmente, el Maestro Higa es el Director Mundial de la World Shorinryu Kyudokan Higa Te Karate-do Federation, también es el Presidente y Director Técnico de la Organización Italiana de Karate-do Kyudokan de Okinawa (OIKKO). Además, fue miembro del Consejo Técnico y Jefe de Árbitros de Karate Tradicional de la World Karate Organization. Sus distinciones no se detienen ahí, dado que fue recibido como Huésped de Honor y Ciudadano Honorario en diferentes ciudades de todo el mundo.</p>
                <p className={styles.peleador__article__text}>A Oscar Higa le gusta hacer incapié en el concepto del empirismo que le enseñó el karate, en el hecho de hacer. Cuenta que durante su adolescencia, su padre siempre le decía &quot;no digas, hacé; no hables, practicá&quot;. Y destaca a varios pensadores que reflexionan al rededor de esta idea, como al artista plástico Pablo Picassom que decía que &quot;La inspiración llega, pero te tiene que encontrar trabajando&quot;, o al sabio y filósofo Confucio, quien dijo &quot;Lo escuché, lo explicaron y me olvidé, lo vi y entendi, lo hice y aprendí&quot;. Según el Maestro Higa, el karate se debe practicar, se debe sentir, se debe vivir.</p>
            </section>
        </main>
    )
}